# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: y:/C++/Uni-CPU/CPURev2/CPURev2.srcs/sources_1/bd/Setup/ip/Setup_auto_pc_0/Setup_auto_pc_0.xci
# IP: The module: 'Setup_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/C++/Uni-CPU/CPURev2/CPURev2.gen/sources_1/bd/Setup/ip/Setup_auto_pc_0/Setup_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Setup_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev2/CPURev2.srcs/sources_1/bd/Setup/ip/Setup_auto_pc_0/Setup_auto_pc_0.xci
# IP: The module: 'Setup_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/C++/Uni-CPU/CPURev2/CPURev2.gen/sources_1/bd/Setup/ip/Setup_auto_pc_0/Setup_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Setup_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
