set_property SRC_FILE_INFO {cfile:Y:/C++/Uni-CPU/LED-TestProject/LED-TestProject.srcs/constrs_1/new/LED_XDC.xdc rfile:../../../LED-TestProject.srcs/constrs_1/new/LED_XDC.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P20 [get_ports led]
