# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Y:/C++/Uni-CPU/CPU_Rev3/CPU_Rev3.srcs/sources_1/bd/CPU/ip/CPU_blk_mem_gen_0_0/CPU_blk_mem_gen_0_0.xci
# IP: The module: 'CPU_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/C++/Uni-CPU/CPU_Rev3/CPU_Rev3.gen/sources_1/bd/CPU/ip/CPU_blk_mem_gen_0_0/CPU_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: Y:/C++/Uni-CPU/CPU_Rev3/CPU_Rev3.srcs/sources_1/bd/CPU/ip/CPU_blk_mem_gen_0_0/CPU_blk_mem_gen_0_0.xci
# IP: The module: 'CPU_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: y:/C++/Uni-CPU/CPU_Rev3/CPU_Rev3.gen/sources_1/bd/CPU/ip/CPU_blk_mem_gen_0_0/CPU_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
