# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Smart_ZYNQ_SP_SL/Petalinux/08_Petalinux_NET_TEST/NET_TEST/NET_TEST.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/ZYNQ_gmii_to_rgmii_0_0.xci
# IP: The module: 'ZYNQ_gmii_to_rgmii_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Smart_ZYNQ_SP_SL/Petalinux/08_Petalinux_NET_TEST/NET_TEST/NET_TEST.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/synth/ZYNQ_gmii_to_rgmii_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_gmii_to_rgmii_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Smart_ZYNQ_SP_SL/Petalinux/08_Petalinux_NET_TEST/NET_TEST/NET_TEST.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/synth/ZYNQ_gmii_to_rgmii_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_gmii_to_rgmii_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Smart_ZYNQ_SP_SL/Petalinux/08_Petalinux_NET_TEST/NET_TEST/NET_TEST.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/synth/ZYNQ_gmii_to_rgmii_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_gmii_to_rgmii_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Smart_ZYNQ_SP_SL/Petalinux/08_Petalinux_NET_TEST/NET_TEST/NET_TEST.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/ZYNQ_gmii_to_rgmii_0_0.xci
# IP: The module: 'ZYNQ_gmii_to_rgmii_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Smart_ZYNQ_SP_SL/Petalinux/08_Petalinux_NET_TEST/NET_TEST/NET_TEST.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/synth/ZYNQ_gmii_to_rgmii_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_gmii_to_rgmii_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Smart_ZYNQ_SP_SL/Petalinux/08_Petalinux_NET_TEST/NET_TEST/NET_TEST.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/synth/ZYNQ_gmii_to_rgmii_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_gmii_to_rgmii_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Smart_ZYNQ_SP_SL/Petalinux/08_Petalinux_NET_TEST/NET_TEST/NET_TEST.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/synth/ZYNQ_gmii_to_rgmii_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZYNQ_gmii_to_rgmii_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
