# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Git/Uni-CPU/CPU_Rev3/CPU_Rev3.srcs/sources_1/bd/CPU/ip/CPU_gmii_to_rgmii_0_0/CPU_gmii_to_rgmii_0_0.xci
# IP: The module: 'CPU_gmii_to_rgmii_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Git/Uni-CPU/CPU_Rev3/CPU_Rev3.gen/sources_1/bd/CPU/ip/CPU_gmii_to_rgmii_0_0/synth/CPU_gmii_to_rgmii_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_gmii_to_rgmii_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Git/Uni-CPU/CPU_Rev3/CPU_Rev3.gen/sources_1/bd/CPU/ip/CPU_gmii_to_rgmii_0_0/synth/CPU_gmii_to_rgmii_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_gmii_to_rgmii_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Git/Uni-CPU/CPU_Rev3/CPU_Rev3.gen/sources_1/bd/CPU/ip/CPU_gmii_to_rgmii_0_0/synth/CPU_gmii_to_rgmii_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_gmii_to_rgmii_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Git/Uni-CPU/CPU_Rev3/CPU_Rev3.srcs/sources_1/bd/CPU/ip/CPU_gmii_to_rgmii_0_0/CPU_gmii_to_rgmii_0_0.xci
# IP: The module: 'CPU_gmii_to_rgmii_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Git/Uni-CPU/CPU_Rev3/CPU_Rev3.gen/sources_1/bd/CPU/ip/CPU_gmii_to_rgmii_0_0/synth/CPU_gmii_to_rgmii_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_gmii_to_rgmii_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Git/Uni-CPU/CPU_Rev3/CPU_Rev3.gen/sources_1/bd/CPU/ip/CPU_gmii_to_rgmii_0_0/synth/CPU_gmii_to_rgmii_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_gmii_to_rgmii_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Git/Uni-CPU/CPU_Rev3/CPU_Rev3.gen/sources_1/bd/CPU/ip/CPU_gmii_to_rgmii_0_0/synth/CPU_gmii_to_rgmii_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_gmii_to_rgmii_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
