@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Oct 16 17:23:40 +0100 2024
REM SW Build 5164865 on Thu Sep  5 14:37:11 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim CPU_wrapper_func_impl -key {Post-Implementation:sim_1:Functional:CPU_wrapper} -tclbatch CPU_wrapper.tcl -protoinst "protoinst_files/CPU.protoinst" -log simulate.log"
call xsim  CPU_wrapper_func_impl -key {Post-Implementation:sim_1:Functional:CPU_wrapper} -tclbatch CPU_wrapper.tcl -protoinst "protoinst_files/CPU.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
