@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Aug 01 21:59:37 +0100 2024
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab --incr --debug typical --relax --mt 2 -L cpu -L gmii_to_rgmii_v4_1_14 -L axi_infrastructure_v1_1_0 -L axi_vip_v1_1_17 -L processing_system7_vip_v1_0_19 -L util_vector_logic_v2_0_4 -L lib_cdc_v1_0_3 -L lib_pkg_v1_0_4 -L fifo_generator_v13_2_10 -L lib_fifo_v1_0_19 -L blk_mem_gen_v8_4_8 -L lib_bmg_v1_0_17 -L lib_srl_fifo_v1_0_4 -L axi_datamover_v5_1_33 -L axi_vdma_v6_3_19 -L axi_lite_ipif_v3_0_4 -L v_tc_v6_1_14 -L v_vid_in_axi4s_v4_0_11 -L v_axi4s_vid_out_v4_0_18 -L v_tc_v6_2_8 -L proc_sys_reset_v5_0_15 -L generic_baseblocks_v2_1_2 -L axi_register_slice_v2_1_31 -L axi_data_fifo_v2_1_30 -L axi_crossbar_v2_1_32 -L axi_protocol_converter_v2_1_31 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot Everything_wrapper_behav cpu.Everything_wrapper cpu.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L cpu -L gmii_to_rgmii_v4_1_14 -L axi_infrastructure_v1_1_0 -L axi_vip_v1_1_17 -L processing_system7_vip_v1_0_19 -L util_vector_logic_v2_0_4 -L lib_cdc_v1_0_3 -L lib_pkg_v1_0_4 -L fifo_generator_v13_2_10 -L lib_fifo_v1_0_19 -L blk_mem_gen_v8_4_8 -L lib_bmg_v1_0_17 -L lib_srl_fifo_v1_0_4 -L axi_datamover_v5_1_33 -L axi_vdma_v6_3_19 -L axi_lite_ipif_v3_0_4 -L v_tc_v6_1_14 -L v_vid_in_axi4s_v4_0_11 -L v_axi4s_vid_out_v4_0_18 -L v_tc_v6_2_8 -L proc_sys_reset_v5_0_15 -L generic_baseblocks_v2_1_2 -L axi_register_slice_v2_1_31 -L axi_data_fifo_v2_1_30 -L axi_crossbar_v2_1_32 -L axi_protocol_converter_v2_1_31 -L uvm -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot Everything_wrapper_behav cpu.Everything_wrapper cpu.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
