# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName cpu
    rt::set_parameter defaultVhdlWorkLib cpu

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_gmii_to_rgmii_0_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_processing_system7_0_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_util_vector_logic_0_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_BUS_0_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_BUS_1_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_BUS_2_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_CU_0_1_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_ALU_0_1_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_MM_0_1_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_BusMerger_0_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_DeviceSelector_0_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_BusMerger_1_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_BusMerger_2_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_DeviceSelector_1_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_DeviceSelector_0_1_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_IOController_0_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_InoutBusSplitter_0_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/realtime/ZYNQ_Dummy_0_0_stub.v
      Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/new/Dummy.v
      y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/synth/ZYNQ.v
      Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/hdl/ZYNQ_wrapper.v
    }
      rt::read_verilog -lib CPU {
      Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/new/CTRL-BUS.v
      Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/new/CU.v
      Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/new/ALU.v
      Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/new/MM.v
      Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/new/Mergers.v
      Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/new/DeviceSelector.v
      Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/new/IOController.v
      Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/new/InoutBusSplitter.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top ZYNQ_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter lint_verbosity true
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "Y:/C++/Uni-CPU/CPURev1/.Xil/Vivado-9612-DESKTOP-PSI4IU2/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
