# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/Everything/ip/Everything_ZYNQ_wrapper_0_0/Everything_ZYNQ_wrapper_0_0.xci
# IP: The module: 'Everything_ZYNQ_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ZYNQ.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ || ORIG_REF_NAME==ZYNQ} -quiet] -quiet

# IP: Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/ZYNQ_gmii_to_rgmii_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_gmii_to_rgmii_0_0 || ORIG_REF_NAME==ZYNQ_gmii_to_rgmii_0_0} -quiet] -quiet

# IP: Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_processing_system7_0_0/ZYNQ_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_processing_system7_0_0} -quiet] -quiet

# IP: Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_util_vector_logic_0_0/ZYNQ_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_util_vector_logic_0_0 || ORIG_REF_NAME==ZYNQ_util_vector_logic_0_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_DVI_Transmitter_0_0/ZYNQ_DVI_Transmitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_DVI_Transmitter_0_0 || ORIG_REF_NAME==ZYNQ_DVI_Transmitter_0_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_vdma_0_0/ZYNQ_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_axi_vdma_0_0 || ORIG_REF_NAME==ZYNQ_axi_vdma_0_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_clk_wiz_0_0/ZYNQ_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_clk_wiz_0_0 || ORIG_REF_NAME==ZYNQ_clk_wiz_0_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_util_vector_logic_0_1/ZYNQ_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_util_vector_logic_0_1 || ORIG_REF_NAME==ZYNQ_util_vector_logic_0_1} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_v_axi4s_vid_out_0_0/ZYNQ_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==ZYNQ_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_v_tc_0_0/ZYNQ_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_v_tc_0_0 || ORIG_REF_NAME==ZYNQ_v_tc_0_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_ps7_0_axi_periph_0/ZYNQ_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZYNQ_ps7_0_axi_periph_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_rst_ps7_0_50M_0/ZYNQ_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_50M_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_mem_intercon_0/ZYNQ_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_axi_mem_intercon_0 || ORIG_REF_NAME==ZYNQ_axi_mem_intercon_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_rst_ps7_0_200M_0/ZYNQ_rst_ps7_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_200M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_200M_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_xbar_0/ZYNQ_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_xbar_0 || ORIG_REF_NAME==ZYNQ_xbar_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_auto_pc_0/ZYNQ_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_auto_pc_0 || ORIG_REF_NAME==ZYNQ_auto_pc_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_auto_pc_1/ZYNQ_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_auto_pc_1 || ORIG_REF_NAME==ZYNQ_auto_pc_1} -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/synth/ZYNQ_gmii_to_rgmii_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_gmii_to_rgmii_0_0 || ORIG_REF_NAME==ZYNQ_gmii_to_rgmii_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/synth/ZYNQ_gmii_to_rgmii_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_gmii_to_rgmii_0_0 || ORIG_REF_NAME==ZYNQ_gmii_to_rgmii_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/synth/ZYNQ_gmii_to_rgmii_0_0_ooc.xdc

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_processing_system7_0_0/ZYNQ_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_axi_vdma_0_0/ZYNQ_axi_vdma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_axi_vdma_0_0 || ORIG_REF_NAME==ZYNQ_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_axi_vdma_0_0/ZYNQ_axi_vdma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_axi_vdma_0_0 || ORIG_REF_NAME==ZYNQ_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_axi_vdma_0_0/ZYNQ_axi_vdma_0_0_ooc.xdc

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_clk_wiz_0_0/ZYNQ_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_clk_wiz_0_0 || ORIG_REF_NAME==ZYNQ_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_clk_wiz_0_0/ZYNQ_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_clk_wiz_0_0 || ORIG_REF_NAME==ZYNQ_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_clk_wiz_0_0/ZYNQ_clk_wiz_0_0_ooc.xdc

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_v_axi4s_vid_out_0_0/ZYNQ_v_axi4s_vid_out_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==ZYNQ_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_v_tc_0_0/ZYNQ_v_tc_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_v_tc_0_0 || ORIG_REF_NAME==ZYNQ_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_rst_ps7_0_50M_0/ZYNQ_rst_ps7_0_50M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_rst_ps7_0_50M_0/ZYNQ_rst_ps7_0_50M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_rst_ps7_0_200M_0/ZYNQ_rst_ps7_0_200M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_200M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_200M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_rst_ps7_0_200M_0/ZYNQ_rst_ps7_0_200M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_200M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_200M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_auto_pc_0/ZYNQ_auto_pc_0_ooc.xdc

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_auto_pc_1/ZYNQ_auto_pc_1_ooc.xdc

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ZYNQ_ooc.xdc

# IP: Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/Everything/ip/Everything_ZYNQ_wrapper_0_0/Everything_ZYNQ_wrapper_0_0.xci
# IP: The module: 'Everything_ZYNQ_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ZYNQ.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ || ORIG_REF_NAME==ZYNQ} -quiet] -quiet

# IP: Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/ZYNQ_gmii_to_rgmii_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_gmii_to_rgmii_0_0 || ORIG_REF_NAME==ZYNQ_gmii_to_rgmii_0_0} -quiet] -quiet

# IP: Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_processing_system7_0_0/ZYNQ_processing_system7_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_processing_system7_0_0} -quiet] -quiet

# IP: Y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_util_vector_logic_0_0/ZYNQ_util_vector_logic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_util_vector_logic_0_0 || ORIG_REF_NAME==ZYNQ_util_vector_logic_0_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_DVI_Transmitter_0_0/ZYNQ_DVI_Transmitter_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_DVI_Transmitter_0_0 || ORIG_REF_NAME==ZYNQ_DVI_Transmitter_0_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_vdma_0_0/ZYNQ_axi_vdma_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_axi_vdma_0_0 || ORIG_REF_NAME==ZYNQ_axi_vdma_0_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_clk_wiz_0_0/ZYNQ_clk_wiz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_clk_wiz_0_0 || ORIG_REF_NAME==ZYNQ_clk_wiz_0_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_util_vector_logic_0_1/ZYNQ_util_vector_logic_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_util_vector_logic_0_1 || ORIG_REF_NAME==ZYNQ_util_vector_logic_0_1} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_v_axi4s_vid_out_0_0/ZYNQ_v_axi4s_vid_out_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==ZYNQ_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_v_tc_0_0/ZYNQ_v_tc_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_v_tc_0_0 || ORIG_REF_NAME==ZYNQ_v_tc_0_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_ps7_0_axi_periph_0/ZYNQ_ps7_0_axi_periph_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZYNQ_ps7_0_axi_periph_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_rst_ps7_0_50M_0/ZYNQ_rst_ps7_0_50M_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_50M_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_axi_mem_intercon_0/ZYNQ_axi_mem_intercon_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_axi_mem_intercon_0 || ORIG_REF_NAME==ZYNQ_axi_mem_intercon_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_rst_ps7_0_200M_0/ZYNQ_rst_ps7_0_200M_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_200M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_200M_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_xbar_0/ZYNQ_xbar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_xbar_0 || ORIG_REF_NAME==ZYNQ_xbar_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_auto_pc_0/ZYNQ_auto_pc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_auto_pc_0 || ORIG_REF_NAME==ZYNQ_auto_pc_0} -quiet] -quiet

# IP: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.srcs/sources_1/bd/ZYNQ/ip/ZYNQ_auto_pc_1/ZYNQ_auto_pc_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_auto_pc_1 || ORIG_REF_NAME==ZYNQ_auto_pc_1} -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/synth/ZYNQ_gmii_to_rgmii_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_gmii_to_rgmii_0_0 || ORIG_REF_NAME==ZYNQ_gmii_to_rgmii_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/synth/ZYNQ_gmii_to_rgmii_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_gmii_to_rgmii_0_0 || ORIG_REF_NAME==ZYNQ_gmii_to_rgmii_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_gmii_to_rgmii_0_0/synth/ZYNQ_gmii_to_rgmii_0_0_ooc.xdc

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_processing_system7_0_0/ZYNQ_processing_system7_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_axi_vdma_0_0/ZYNQ_axi_vdma_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_axi_vdma_0_0 || ORIG_REF_NAME==ZYNQ_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_axi_vdma_0_0/ZYNQ_axi_vdma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_axi_vdma_0_0 || ORIG_REF_NAME==ZYNQ_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_axi_vdma_0_0/ZYNQ_axi_vdma_0_0_ooc.xdc

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_clk_wiz_0_0/ZYNQ_clk_wiz_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_clk_wiz_0_0 || ORIG_REF_NAME==ZYNQ_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_clk_wiz_0_0/ZYNQ_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_clk_wiz_0_0 || ORIG_REF_NAME==ZYNQ_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_clk_wiz_0_0/ZYNQ_clk_wiz_0_0_ooc.xdc

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_v_axi4s_vid_out_0_0/ZYNQ_v_axi4s_vid_out_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==ZYNQ_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_v_tc_0_0/ZYNQ_v_tc_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_v_tc_0_0 || ORIG_REF_NAME==ZYNQ_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_rst_ps7_0_50M_0/ZYNQ_rst_ps7_0_50M_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_rst_ps7_0_50M_0/ZYNQ_rst_ps7_0_50M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_50M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_rst_ps7_0_200M_0/ZYNQ_rst_ps7_0_200M_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_200M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_200M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_rst_ps7_0_200M_0/ZYNQ_rst_ps7_0_200M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_200M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_200M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_auto_pc_0/ZYNQ_auto_pc_0_ooc.xdc

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ip/ZYNQ_auto_pc_1/ZYNQ_auto_pc_1_ooc.xdc

# XDC: y:/C++/Uni-CPU/CPURev1/PYNQ_CONFIG.gen/sources_1/bd/ZYNQ/ZYNQ_ooc.xdc
